- repository: autowarefoundation/sync-file-templates
  source-dir: sources
  files:
    - source: CODE_OF_CONDUCT.md
    - source: CONTRIBUTING.md
    - source: DISCLAIMER.md
    - source: LICENSE
    - source: .github/ISSUE_TEMPLATE/config.yml
    - source: .github/ISSUE_TEMPLATE/task.yaml
    - source: .github/dependabot.yaml
    - source: .github/pull_request_template.md
    - source: .github/stale.yml
    - source: .github/workflows/comment-on-pr.yaml
    - source: .github/workflows/pre-commit-optional.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .github/workflows/sync-files.yaml
    - source: .markdown-link-check.json
      pre-commands: |
        sd -s -- \
        '     "pattern": "^http://localhost"' \
        '     "pattern": "^https://www\\.autosar\\.org/*"
            },
            {
              "pattern": "^http://localhost"' \
          {source}
    - source: .markdownlint.yaml
    - source: .pre-commit-config.yaml
    - source: .pre-commit-config-optional.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml
    - source: setup.cfg

- repository: autowarefoundation/autoware-documentation
  files:
    - source: mkdocs-base.yaml
      dest: mkdocs.yaml
      pre-commands: |
        sd "  - macros" "  - macros:\n      include_yaml:\n        - autoware_interfaces: yaml/autoware-interfaces.yaml" {source}
