# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for all rules.
default: true
MD013: false
MD024:
  siblings_only: true
MD029:
  style: ordered
MD033: false
MD041: false
MD046: false
MD049: false
