@startuml

skinparam SequenceMessageAlign center
participant "Application" as app
participant "AD API" as adapi

app -> adapi ++: /api/manual/remote/control_mode/select
return
adapi -> app: /api/manual/remote/control_mode/status

par
  app -> adapi: /api/manual/remote/command/**
else
  adapi -> app: /api/vehicle/status
end

@enduml
