name: delete-closed-pr-docs

on:
  schedule:
    - cron: 0 19 * * * # run at 4 AM JST
  workflow_dispatch:

jobs:
  delete-closed-pr-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Delete closed PR docs
        uses: autowarefoundation/autoware-github-actions/delete-closed-pr-docs@tier4/proposal
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
