name: spell-check

on:
  pull_request:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run spell-check
        uses: autowarefoundation/autoware-github-actions/spell-check@tier4/proposal
        with:
          cspell-json-url: https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json
